/******************************************************************************
cppa-make.c -- This module of the cppa program handles 'make' mode.
$Id: cppa-make.c 2717 2011-06-20 17:49:43Z miles $
Sunburn $Source$
******************************************************************************/
#include "cppa.h"

int  make_show_target = TRUE;
char cppfilename[LINE_CHARS_MAXCNT];
char madefilename[LINE_CHARS_MAXCNT];
char makefilename[LINE_CHARS_MAXCNT];
char *targfilename;

#define MAKE_STATE_UNSTARTED 0
#define MAKE_STATE_HEADER    1
#define MAKE_STATE_TOPDEP    2
#define MAKE_STATE_TOPCMDS   3
#define MAKE_STATE_MAKE      4
#define MAKE_STATE_BODY      5
int make_state = MAKE_STATE_UNSTARTED;
int makefile_in_topdep = FALSE;

char poundline[] = "##############################################################################";


/******************************************************************************
Make--- Handles shell command "cppa make <cppafilename> > <makefilename>
        Generates make file.
This is the 'main---' function in this module.
******************************************************************************/
Make() {
  char line[LINE_CHARS_MAXCNT];
  int  sscanf_ret;

  if (cppafile == stdin) {
    printf("Error: Input file must be specified on the command line.\n");
    exit(1);
  }

  strcpy(makefilename, cppafilename);
  tail = strrchr(makefilename, '.');
  if ((tail != NULL) && STREQ(tail, ".cppa")) tail[0] = '\0';
  strcpy(cppfilename, makefilename);
  strcpy(madefilename, makefilename);
  strcat(madefilename, ".made");
  strcat(makefilename, ".make");
  strcat(cppfilename, ".cpp");

  for (tindex = 0; tindex < target_next; tindex++) target_sym_cnt[tindex] = 0;

  target_next = 0;
  while (Gil_Get_Line(line)) {
    sscanf_ret = sscanf(line, "%s %s", directive, cppacmd);
    if (STREQ(directive, "#cppa" ) && (sscanf_ret > 0)) {
      if STREQ(cppacmd, "target") Make_Target(line);
      else if STREQ(cppacmd, "makenoshowtarget") 
                                                      make_show_target = FALSE;
      else if STREQ(cppacmd, "makeheader"    ) Make_Header();
      else if STREQ(cppacmd, "maketopdep"    ) Make_Topdep(line);
      else if STREQ(cppacmd, "maketopcmds"   ) Make_Topcmds();
      else if STREQ(cppacmd, "makemake"      ) Make_Make();
      else if STREQ(cppacmd, "makebody"      ) Make_Body();
      else if STREQ(cppacmd, "makelines"     ) Make_Lines();
      else { /* Ignore other #cppa directives */ }
    } /* (strcmp #cppa) */
  } /* (while (Gil_Get_Line...)) */

  if (make_state == MAKE_STATE_UNSTARTED) {
    if (debug>0) fprintf(stderr, "Making everything...\n");
    Make_Everything();
  }

  if (make_state < MAKE_STATE_BODY) fprintf(stderr, 
    "\n\n    CPPA WARNING: Missing make statements? (state = %d)\n\n\n",
    make_state);
    
} /* Make() */


/******************************************************************************
Make_Target--- Handle the "#cppa target" directive.
******************************************************************************/
Make_Target(char *line) {
  int sscanf_ret;

  if (target_next >= TARGET_MAXCNT) {
    fprintf(stderr, "\nTARGETS EXCEED MAXIMUM (%d)\n\nAborting...\n", 
	    TARGET_MAXCNT);
    abort();
  }
  sscanf_ret = sscanf(line, "%s %s %s %s %s %s %s %s %s %s", 
		      directive, cppacmd, 
		      target[target_next][0], target[target_next][1], 
		      target[target_next][2], target[target_next][3], 
		      target[target_next][4], target[target_next][5], 
		      target[target_next][6], target[target_next][7]);

  if (sscanf_ret < 4) {
    fprintf(stderr, "Too few symbols in '#cppa target' directive.\n");
    fprintf(stderr, "CPPA ABORTION.\n");
    exit(1);
  }
  target_sym_cnt[target_next] = sscanf_ret - 2;
  target_next++;

  if (debug>1) fprintf(stderr,"looking for target #%d\n", target_next);

} /* Make_Target() */

/******************************************************************************
Make_Header--- Generate the make file header lines
******************************************************************************/
Make_Header() {

  if (make_state != MAKE_STATE_UNSTARTED) fprintf(stderr, 
    "\n\n    CPPA WARNING: makeheader out of sequence.\n\n\n");
  make_state = MAKE_STATE_HEADER;

  printf("%s\n", poundline);
  printf("# DO NOT EDIT THIS FILE DIRECTLY (%s)\n", makefilename);
  printf("#\n");
  printf("# This make file was generated automatically from %s\n",
	 cppafilename);
  printf("# by the cppa program.  (To regenerate it, you can\n");
  printf("# do 'cppa make %s >! %s'\n", cppafilename, makefilename);
  if (target_next) {
    printf("#\n# This make file is used to make the following files:\n");
    for (tindex = 0; tindex < target_next; tindex++) {
      if (tindex % 2) printf("    %-25s\n", target[tindex][0]);
      else        printf("#     %-25s", target[tindex][0]);
    }
    if (tindex % 2) printf("\n");
    printf("# \n");
  }
  printf("%s\n", poundline);
}


/******************************************************************************
Make_Topdep--- Generate (part of) the top dependency line for the make 
               file.  No newline is included so that the user can add 
               additional items to the list if they wish.  (Using makelines.)
******************************************************************************/
Make_Topdep(char *line) {
  int sym_cnt;
  int sindex;

  if (make_state > MAKE_STATE_TOPDEP) fprintf(stderr, 
      "\n\n    CPPA WARNING: topdef out of sequence?\n\n\n");
  make_state = MAKE_STATE_TOPDEP;

  printf("\ntop: %s\n", madefilename);

  printf("\n%s:", madefilename);
  for (tindex = 0; tindex < target_next; tindex++) printf(" %s", target[tindex][0]);

  /* Extract and addextra symbols from "#cppa topdep" line */
  {
    sym_cnt = Get_Syms(&line[1]);
    sindex = 2; /* Start with the 3rd symbol (after "cppa" and "make_topdep")*/
    while (sindex < sym_cnt) {
      if STREQ(syma[sindex], makefilename) makefile_in_topdep = TRUE;
      printf(" %s", syma[sindex++]);
    }
  printf("\n");
  }
}

/******************************************************************************
Make_Topcmds--- Generate commands to follow the top dependency line.
******************************************************************************/
Make_Topcmds() {

  if (make_state != MAKE_STATE_TOPDEP) fprintf(stderr, 
      "\n\n    CPPA WARNING: topcmds not preceded by topdep\n\n\n");
  make_state = MAKE_STATE_TOPCMDS;

  if (make_show_target) 
    printf("\tm=\"#### %s #### %s ####\"\n", makefilename, madefilename);

  printf("\t- chmod u+w %s\n", 
	 madefilename, madefilename);
  printf("\tdate > %s\n", madefilename);
  printf("\tchmod ugo-w %s\n", madefilename);
  /* $$$TBD printf("\n"); */
}


/******************************************************************************
Make_Make--- Generate the lines in the make file that generate the make file.
             This procedure must be careful to avoid clobbering the current
             make file.  Instead of clobbering it, it is just renamed so that
             the make program can continue using its file handle.
******************************************************************************/
Make_Make() {

  if (make_state != MAKE_STATE_TOPCMDS) fprintf(stderr,
    "\n\n    CPPA WARNING: makemake not after maketopdep.\n\n\n");
  make_state = MAKE_STATE_MAKE;

  if (! makefile_in_topdep) {
    fprintf(stderr, 
	    "\n\n     CPPA WARNING: %s not included in top dependency.\n\n\n", 
	    makefilename);
  }

  printf("\n%s: %s\n", makefilename, cppafilename);
  printf("\t- chmod u+w %s~\n", makefilename);
  printf("\t- mv %s %s~\n", makefilename, makefilename);
  printf("\tcppa make %s > %s\n", cppafilename, makefilename);
  printf("\tchmod ugo-w %s\n", makefilename);
}


/******************************************************************************
Make_Body--- Generate target lines for the make file.
******************************************************************************/
Make_Body() {

  if (make_state < MAKE_STATE_TOPCMDS) {
    fprintf(stderr,"\n\n");
    fprintf(stderr,
      "    CPPA WARNING: #cppa makebody not after maketopcmds nor makemake\n");
    fprintf(stderr,"\n\n");
  }
  make_state = MAKE_STATE_BODY;

  printf("\n%s: %s %s\n", cppfilename, cppafilename, makefilename);
  if (make_show_target)
    printf("\tm=\"#### %s #### %s ####\"\n", makefilename, cppfilename);
  printf("\t- chmod u+w %s\n", cppfilename);
  printf("\tcppa pre %s > %s\n", cppafilename, cppfilename);
  printf("\tchmod ugo-w %s\n", cppfilename);

  /* Generate target lines for each target */
  {
    for (tindex = 0; tindex < target_next; tindex++) {
      targfilename = target[tindex][0];
      printf("\n%s: %s %s\n", targfilename, cppfilename, makefilename);
      if (make_show_target)
	printf("\tm=\"#### %s #### %s ####\"\n", 
	       makefilename, targfilename);
      printf("\t- chmod u+w %s\n", targfilename);
      printf("\tcpp -C -P");
      for (tcindex = 1; tcindex < target_sym_cnt[tindex]; tcindex++) {
	printf(" -D%s", target[tindex][tcindex]);
      }
      printf(" %s | \\\n", cppfilename);
      printf("            cppa post > %s\n", targfilename);
      printf("\tchmod ugo-w %s\n", targfilename);
    }
  }

  target_next = 0; /* None pending */
}


/******************************************************************************
Make_Lines--- Pass lines to stdout (for .make file).
              These can be inserted in any order.
******************************************************************************/
Make_Lines() {

  char makeline[LINE_CHARS_MAXCNT];

  Gil_Get_Line(makeline);
  while (strncmp(makeline, "#cppa endmakelines", 18) != NULL) {
    printf("%s\n", makeline);
    Gil_Get_Line(makeline);
  }
}

/******************************************************************************
Make_Everything--- If they don't explicitly use any #cppa make* directives,
                   then do it all for them.
******************************************************************************/
Make_Everything() {
  Make_Header();
  strcpy(tempstr, "#cppa maketopdep ");
  strcat(tempstr, makefilename);
  Make_Topdep(tempstr);
  Make_Topcmds();
  Make_Make();
  Make_Body();
}
